name: Postman API Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  api-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman and Reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Create Report Directory
        run: mkdir -p newman-report

      - name: Run Postman Collection
        run: |
          newman run postman/collection.json \
          -e postman/environment.json \
          -r htmlextra \
          --reporter-htmlextra-export newman-report/index.html \
          --reporter-htmlextra-title "Restful Booker API Test Report"

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./newman-report
          destination_dir: api-tests